#!/usr/bin/env ruby

start = Time.now
source = File.expand_path "#{__dir__}/../app/javascript/opal"
target = File.expand_path "#{__dir__}/../app/assets/builds/opal"
basename = "application"

require 'fileutils'
FileUtils.mkdir_p target
File.write "#{target}/#{basename}.js", ""

p source => target
p "#{source}/#{basename}.js.rb" => ["#{target}/#{basename}.js", "#{target}/#{basename}.js.map"]
# By default will write the source-map in a separate file
# with the "--map" option, while the "--no-source-map"
# option refers to not including the inline source-map.
system(
  "opal",
  "--rbrequire=opal-browser",
  "--include=#{source}",
  "--no-source-map",
  "--map=#{target}/#{basename}.js.map",
  "--compile",
  "#{source}/#{basename}.js.rb",
  "--output=#{target}/#{basename}.js",
  *ARGV,
) or abort("[opal] Compilation failed: #{$?}")

# File.write(
#   "#{target}/#{basename}.js",
#   "\n//# sourceMappingURL=./#{basename}.js.map\n",
#   mode: "ab",
# )
#
# puts "[opal] Built in #{"%.3f" % (Time.now - start)}s"
#
# # When watching, after the first run it will call itself without the
# # --watch option.
# if ARGV.include? "--watch"
#   puts "[opal] Watching..."
#
#   require "listen"
#   require "rbconfig"
#
#   listener = Listen.to(source) do |*args|
#     puts "[opal] Changed #{args.flatten.join(", ")}"
#     system RbConfig.ruby, __FILE__
#   end
#
#   listener.start
#   sleep
#   exit
# end
